### ISSUE TITLE
myshow.py  for a 3D image display

### ISSUE THREAD

**Issue by subhajitchatu** [InsightSoftwareConsortium/SimpleITK-Notebooks#123]
Hi,

If I want to show a 3D image let say (512*512)*60 slices. The function myshow3D() is failed to give any output rendering the 3D image. I think there is some conceptual issue. Will it be able to show any kind of 3D image, like [http://docs.enthought.com/mayavi/mayavi/](url) is for brain(not accurate though). Is there any other way to visualize a stack of images in 3D space?

Thanks

**Comment by zivy** [comment]
Please provide more details so that we can address the specific problem. 

In general, myshow3d should be able to display all 3D images you load with SimpleITK. If you want something slightly more sophisticated please take a look at the MultiImageDisplay found in the gui.py module. This is used in the [30_Segmentation_Region_Growing](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/blob/master/Python/30_Segmentation_Region_Growing.ipynb) notebook.

Be aware that we only provide basic viewing capabilities as our focus is on the segmentation and registration and not on visualization.  If you want to develop feature rich visualization then I would suggest you look into [VTK](http://www.vtk.org/).

**Comment by subhajitchatu** [comment]
Thanks a lot @zivy . 
When I am using myshow3d(image1).
Image1 is a Sitk image.
Image1.GetDimension() = (512,512,60)
But it is displaying a window with middle slice. Strange!

Any other suggestion?

**Comment by zivy** [comment]
The myshow3D should display the middle slice and a slider which allows you to scroll through the stack. The slider is from the ipywidgets package which is a notebook extension. If you are working with plain Python you should enable the extension, [per our instructions](https://github.com/zivy/SimpleITK-Notebooks/tree/master/Python#plain-python):
jupyter nbextension enable --py --sys-prefix widgetsnbextension

If you are working with the Anaconda distribution then the extension is enabled by default. Other than this I can't think of a reason the slider is not displayed.

**Comment by subhajitchatu** [comment]
Thanks @zivy 

I have tried it many times before

my python version : 2.7.9
Ubuntu 15.04
Jupyter version 4.3.0

 
sudo jupyter nbextension enable --py --sys-prefix widgetsnbextension
Enabling notebook extension jupyter-js-widgets/extension...
      - Validating: OK

when I tried to execute
myshow3d(original_image);
Message on console:
Widget Javascript not detected.  It may not be installed or enabled properly.

and an image is being displayed with only middle slice, No slider was there.

Any suggestion to fix this issue.

Thanks

**Comment by zivy** [comment]
Google got me to [this page](https://github.com/jupyter-widgets/ipywidgets/issues/669) discussing the problem. Please try the solutions suggested there. As this is a Jupyter notebooks issue and not a SimpleITK one I am closing the discussion.
