### ISSUE TITLE
FFD using Bspline throwing  _bad_alloc error

### ISSUE THREAD

**Issue by subhajitchatu** [InsightSoftwareConsortium/SimpleITK-Notebooks#136]
Hi @zivy
I have found that there are two way to configure mesh for doing registration using BSpline.
1. `transfromDomainMeshSize=[10]*moving.GetDimension()`
   `tx = sitk.BSplineTransformInitializer(fixed, transfromDomainMeshSize )`
2. `grid_physical_spacing = [50.0, 50.0, 50.0]`
    `image_physical_size = [size*spacing for size,spacing in zip(fixed_image.GetSize(),
     fixed_image.GetSpacing())]`
    `mesh_size = [int(image_size/grid_spacing + 0.5) \
                 for image_size,grid_spacing in zip(image_physical_size,grid_physical_spacing)]`

    `initial_transform = sitk.BSplineTransformInitializer(image1 = fixed_image, 
                                                                    transformDomainMeshSize = mesh_size, order=3)`  

## Problem
My image dimension is [480 480 60]   
In the 1st case If I put `transfromDomainMeshSize = [8]*moving.GetDimension()` then it gives me _bad_alloc error, while I put 6 , it started working but it takes excessive amount of time.

In the 2nd case, It does not work for < 70mm spacing, it gives error in registration.execute().

## Doubts

1. What's the difference between these two and which one is recommended?
2. If I want to add Affine transform as global registration, then FFD using B-spline, what should I do ?

Thanks

**Comment by zivy** [comment]
@subhajitchatu,
The code snippets you are citing are not different ways of using the BSplineTransformInitializer, they are different ways of computing the grid size of the FFD mesh:
1. Python shorthand for: use a mesh of size 10,10,10 .
2. More involved computation that sets the distance between neighboring mesh control points to 50mm. This means that we start with the desired mesh spacing and compute the number of control points per axis, which is different per axis as they have to cover the physical space of the image.

To add an Affine transform as the initial transform and then use FFD for optimization you need to:
```
# Add initial affine transformation which WILL NOT be modified
registration_method.SetMovingInitialTransform(my_affine_transform) 

# Add initial bspline transform which WILL be modified.
registration_method.SetInitialTransform(my_bspline_transform)
```

With regard to the possible bug, please create a minimum working example and submit a bug report on the [SimpleITK issue tracker](https://github.com/SimpleITK/SimpleITK/issues)

Finally, if you have additional SimpleITK related questions please use the [ITK mailing list](https://itk.org/ITK/help/mailing.html) so that others may benefit from the question and answer, and other users and maintainers will also participate in the conversation.
