### ISSUE TITLE
Error while executing registration

### ISSUE THREAD

**Issue by subhajitchatu** [InsightSoftwareConsortium/SimpleITK-Notebooks#146]
Hi @zivy ,

I was using some registration methods like bspline, demons etc. Suddenly I have encountered the below problem while going to execute registration and after printing the error on terminal, the code exits. What could be the possible reason and how I can correct the issue?

**Error**

`File "/usr/local/lib/python2.7/dist-packages/SimpleITK/SimpleITK.py", line 11064, in Execute
    return _SimpleITK.ImageRegistrationMethod_Execute(self, fixed, moving)
RuntimeError: Exception thrown in SimpleITK ImageRegistrationMethod_Execute: /home/subha/build/ITK/Modules/Core/Common/src/itkMultiThreader.cxx:416:
itk::ERROR: MultiThreader(0x4cf8d60): Exception occurred during SingleMethodExecute`

Thanks

Regards
Subhajit

**Comment by zivy** [comment]
Hi @subhajitchatu 

From the error I can see you compiled SimpleITK from source, other than that I don't have enough information. I'm closing this issue here as it is not notebook related.

Please post the question on the [SimpleITK issue tracker](https://github.com/SimpleITK/SimpleITK/issues) and provide a minimal working example which produces the error so that we can look into it.
