### ISSUE TITLE
sitk.show never stops running in Jupyter

### ISSUE THREAD

**Issue by sandraMarcadent** [InsightSoftwareConsortium/SimpleITK-Notebooks#228]
Hello,

I have installed 3D Slicer and Sitk on my Windows 10 (Python 3.7.1, Sitk 1.2.0) computer for image registration tasks; those notebooks are really helpfull, so thanks a lot for the authors, however, I just have an issue when running sitk.show() on a jupyter cell, indeed it never stops running and I have to shutdown the notebook manually to explore the next cells...

Any suggestion will be appreciated,
Thank you.

**Comment by zivy** [comment]
Hello @sandraMarcadent 

I am guessing you are working on a windows system. There [was a bug](https://github.com/SimpleITK/SimpleITK/issues/661) with the Show command on windows which has since been fixed. 

You have three options:

1. Don't use Show for now and wait for the upcoming minor release (~next month).

2. If you are comfortable with compiling the toolkit yourself (you have Cmake, git, a compiler):
a. For vanilla Python distribution you can follow the instructions found [here](https://simpleitk.readthedocs.io/en/master/Documentation/docs/source/building.html#building-using-superbuild).
  b. If you are working with Conda you can use the conda recipe found [here](https://github.com/SimpleITK/SimpleITKCondaRecipe). You will have to edit the meta.yaml file based on the instructions so that you are compiling the latest commit.

3. You are in a hurray but don't want to wait for the minor release. The following is a stopgap solution that allows you to code as if Show works:
```
# Override the Show method to WriteImage at the top of the notebook
sitk.Show = sitk.WriteImage

#Code using "Show" as usual
img = sitk.Image([32,32], sitk.sitkUInt8)
sitk.Show(img, 'my_image.mha')
```

With the overriding, the code above will write the image to disk and then you can open it with Fiji or any other viewer you want, no hanging. Once the show command is fixed and you remove the single line at the top of the notebook you won't need to change your code. The Fiji viewer will open the image and the title will be "my_image.mha".

Please close the issue if these resolved your problem.
