### ISSUE TITLE
 How to set an environment variable to point to 3D Slicer?

### ISSUE THREAD

**Issue by jumbojing** [InsightSoftwareConsortium/SimpleITK-Notebooks#234]
I want to set 3D Slicer as the default viewerHow to set an environment variable to point to 3D Slicer?

**Comment by zivy** [comment]
Hello @jumbojing ,

You have several options.  
1. If you are inside a notebook (doesn't matter which operating system):
```
%env SITK_SHOW_COMMAND path_to_slicer
```
2. If on mac/unix, temporary setting from the command line or for permanent setting add it to your .bashrc file :
```
export SITK_SHOW_COMMAND=path_to_slicer
```
3. If on windows, from the command prompt:
```
setx SITK_SHOW_COMMAND path_to_slicer
```
Hopefully this resolves your issue. If it does, please close the issue. If not, please provide additional details (particularly operating system) so that we can help you.

**Comment by jumbojing** [comment]
> setx SITK_SHOW_COMMAND ”C:\Program Files\Slicer 4.9.0-2017-10-31\Slicer.exe“

Thanks！
