### ISSUE TITLE
read DICOM series

### ISSUE THREAD

**Issue by Phoebegit** [InsightSoftwareConsortium/SimpleITK-Notebooks#253]
Hello，
  When I running the code of 03_Image_Details in jupyter notebook, there has a error about reader.GetGDCMSeriesFileName or reader.GetGDCMSeriesIDs, these functions return empty. but there are DICOM files in related path.

![image](https://user-images.githubusercontent.com/31639780/75657189-986ca080-5ca0-11ea-9c63-0f30b0d9b95f.png)

  
Is it about the jupyter notebook version or other reason?

I think the solution of this problem is important to me, because reading series DICOM files will be used in next tutorial.

**Comment by zivy** [comment]
Hello @Phoebegit,

It could be that there was an issue with downloading the DICOM data. Were you online when you ran the notebook? We expect that you are, so that the call to `fdata` at the top of this cell downloads the images from an online resource.

Please check that there are DICOM files in the expected location:
".../SimpleITK-Notebooks/Data/CIRS057A_MR_CT_DICOM/"

If the directory ".../CIRS057A_MR_CT_DICOM/" doesn't exist, you can rerun the cell so that the download happens and creates the directory.

If this doesn't resolve the issue, please provide additional details.

**Comment by Phoebegit** [comment]
Hello @zivy 

Thanks for your reply。
I am online when I ran the notebook and There are DICOM files in path"...\SimpleITK-Notebooks-master\Data\CIRS057A_MR_CT_DICOM", As shown below：
![image](https://user-images.githubusercontent.com/31639780/75737104-ee415700-5d39-11ea-8922-ea1de35f0056.png)

the next picture shows the error of code in details

![image](https://user-images.githubusercontent.com/31639780/75738322-f8188980-5d3c-11ea-9796-51e79e73cd41.png)



**Is this becasue the path name contains chinese?**

By the way, when I ran the code `img = sitk.ReadImage(fdata('training_001_mr_T1.mha'))` , there was a error. when I modified the code as `fdata('training_001_mr_T1.mha')
img = sitk.ReadImage(('../Data/training_001_mr_T1.mha'))`,there was no problem.


![image](https://user-images.githubusercontent.com/31639780/75737718-6fe5b480-5d3b-11ea-8ce7-82841b572a86.png)


Thanks very much!

**Comment by Phoebegit** [comment]
Ok!   This is really because there is Chinese in the path. When I modifed the path name to all English, the code ran successfully.

The problem is solved!

Thanks again!
