### ISSUE TITLE
Differences between demons metric and demons registration filters

### ISSUE THREAD

**Issue by esgomezm** [InsightSoftwareConsortium/SimpleITK-Notebooks#291]
Hi there! 

I'm trying to understand the differences between using the `DemonsMetric` in the registration method and `DemonsRegistrationFilter` [Notebook 66](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/blob/master/Python/66_Registration_Demons.ipynb).

In the notebooks, it is said that the latter is not part of the registration framework, but technically, when implementing a custom `multiscale_demons`, the registration filter is used as the registration algorithm. Also, at [SimpleITK documentation](https://simpleitk.readthedocs.io/en/master/link_DemonsRegistration1_docs.html) it's said that the registration filter computes the classic Demons registration algorithm. 
So wouldn't both the latter and the former be similar? Might the main difference rely on the optimizer? Could you please point me to the technical definition of the DemonsMetric and the filters, used in SimpleITK?

Thank you!

**Comment by zivy** [comment]
Hello @esgomezm,

The 'SetMetricAsDemons' is an adaptation of the original Demons algorithm to the ITK registration framework. The `DemonsRegistrationFilter` shown in notebook 66 is the standalone version of the same algorithm. As these are independent implementations they will likely differ in results and runtime. You will need to evaluate this on your data.

The other standalone Demons Filters mentioned in notebook 66 are variations/improvements of the original. If you need to enforce diffeomorphism or want to use symmetric forces you'll need to use those filters.

The duplication is partly due to the organic growth of the toolkit over the years (2021 marks twenty years since the first release of ITK).

Hopefully this clarifies things.

**Comment by esgomezm** [comment]
Hello @zivy,

Thank you for such a quick response. 
> The 'SetMetricAsDemons' is an adaptation of the original Demons algorithm to the ITK registration framework.

Then, could I assume that it implements the method in the original paper? 

> As these are independent implementations they will likely differ in results and runtime. You will need to evaluate this on your data.

Yes, I wanted to ensure that the differences were due to the implementation and that there weren't variations w.r.t. the original method. Also, can I change the optimizer when using the filters? This could also make the method perform differently.

> The other standalone Demons Filters mentioned in notebook 66 are variations/improvements of the original. If you need to enforce diffeomorphism or want to use symmetric forces you'll need to use those filters.

Ok! This one was more clear to me :)

> The duplication is partly due to the organic growth of the toolkit over the years (2021 marks twenty years since the first release of ITK).

Congrats! :clap:

**Comment by zivy** [comment]
Hello @esgomezm,

Yes, the `SetMetricAsDemons` is an implementation of the original paper. As it is part of the registration framework you can modify the optimizer and select sampling strategy, sampling percentage etc. . These features were not part of the original algorithm, and are not available for the corresponding standalone filter. For all standalone filters there is limited access to the optimization process (number of iterations etc. as part of the filter settings).
