### ISSUE TITLE
Trouble getting external viewer to work

### ISSUE THREAD

**Issue by jslavin** [InsightSoftwareConsortium/SimpleITK-Notebooks#303]
Hi,
I downloaded the notebooks (actually cloned the repository) and also downloaded Fiji. Most things work but I can't get the external viewer to work. I get the following error after executing the third cell in 00_Setup notebook:

RuntimeError                              Traceback (most recent call last)
<ipython-input-4-68c09ab29a45> in <module>
      8 # NOTE: The debug information is printed to the terminal from which you launched the notebook
      9 #       server.
---> 10 sitk.Show(sitk.ReadImage(fetch_data("SimpleITK.jpg")), "SimpleITK Logo", debugOn=True)

/export/slavin/anaconda3/envs/sitkpy/lib/python3.8/site-packages/SimpleITK/SimpleITK.py in Show(*args, **kwargs)
   5423 def Show(*args, **kwargs):
   5424     r"""Show(Image image, std::string const & title="", bool const debugOn=itk::simple::ProcessObject::GetGlobalDefaultDebug())"""
-> 5425     return _SimpleITK.Show(*args, **kwargs)
   5426 class ImageFileWriter(ProcessObject):
   5427     r"""Proxy of C++ itk::simple::ImageFileWriter class."""RuntimeError: Exception thrown in SimpleITK Show: ../../Code/IO/src/sitkImageViewer.cxx:620:
sitk::ERROR: No ImageJ/Fiji application found.

I've set:
%env SITK_SHOW_COMMAND ~/.local/Fiji.app/ImageJ-linux64
which is where the Fiji code is located. I can launch Fiji/ImageJ from the command line with no problems. So where am I going wrong?

**Comment by zivy** [comment]
Hello @jslavin,

The problem is that the `env` magic doesn't expand the `~` to the explicit path. Either use the explicit path to your home directory or use the `os` package so that it works for all users, in which case Fiji is always expected to be in a fixed location relative to the home directory:
```
import os
%env SITK_SHOW_COMMAND os.path.join(os.environ['HOME'],'.local/Fiji.app/ImageJ-linux64')
```
Note that SimpleITK searches for the viewer in specific default locations, [see FAQ for details](https://simpleitk.readthedocs.io/en/master/faq.html#why-isn-t-fiji-or-imagej-found-by-the-show-function-runtimeerror-exception-thrown).

**Comment by jslavin** [comment]
Ah, okay. Missed that FAQ. It's working now. I moved the Fiji.app directory it to $HOME/bin as the path of least resistance. Thanks for the help.
