### ISSUE TITLE
Inconsistency in distance measures in segmentation evaluation notebook

### ISSUE THREAD

**Issue by IlvaHou55** [InsightSoftwareConsortium/SimpleITK-Notebooks#345]
Hi,

For the evaluation of a segmentation task, I used your segmentation evaluation notebook to derive distance-based metrics. However, the values were lower than I expected (a mean surface distance in the order of 1,3 mm). After a thorough analysis, I found out some inconsistencies and was wondering if someone can help me out on this. 

For my specific task, I have two RTSTRUCT files containing the ground-truth and auto-segmented liver. I read them using the [RT-utils toolbox](https://github.com/qurit/rt-utils), after which they are numpy masks. I will attach these numpy masks for reproducability ([contours.zip](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/files/8231775/contours.zip)).

Afterwards I convert the arrays to a simple ITK image by:

```
cont_auto = sitk.GetImageFromArray(cont_auto_numpy.transpose())
cont_auto.SetOrigin(dicom_image.GetOrigin())
cont_auto.SetSpacing(dicom_image.GetSpacing())
cont_auto.SetDirection(dicom_image.GetDirection())
cont_auto = sitk.Cast(cont_auto, sitk.sitkUInt16) 
```

For reproducability the values of the origin, spacing and direction of the dicom image corresponding to the RTStructs are:
- Origin: (-209.45181655884, -178.75591659546, 223.45248413086)
- Spacing: (2.0, 2.0, 4.0)
- Direction: (1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0)

The same step and values are applied to the ground-truth contour (cont_gt).

Next, I follow the steps from the [notebook](http://insightsoftwareconsortium.github.io/SimpleITK-Notebooks/Python_html/34_Segmentation_Evaluation.html):

```
gt_distance_map = sitk.Abs(sitk.SignedMaurerDistanceMap(cont_gt, squaredDistance=False, useImageSpacing=True))
gt_surface = sitk.LabelContour(cont_gt)
        
statistics_image_filter = sitk.StatisticsImageFilter()
statistics_image_filter.Execute(gt_surface)
num_gt_surface_voxels = int(statistics_image_filter.GetSum()) 
        
auto_distance_map = sitk.Abs(sitk.SignedMaurerDistanceMap(cont_auto, squaredDistance=False, useImageSpacing=True))
auto_surface = sitk.LabelContour(cont_auto)
        
statistics_image_filter.Execute(auto_surface)
num_auto_surface_voxels = int(statistics_image_filter.GetSum())
        
auto2gt_distance_map = gt_distance_map*sitk.Cast(auto_surface, sitk.sitkFloat32)
gt2auto_distance_map = auto_distance_map*sitk.Cast(gt_surface, sitk.sitkFloat32)
        
auto2gt_distance_map_arr = sitk.GetArrayViewFromImage(auto2gt_distance_map)
auto2gt_distances = list(auto2gt_distance_map_arr[auto2gt_distance_map_arr!=0]) 
auto2gt_distances = auto2gt_distances + \
                            list(np.zeros(num_auto_surface_voxels - len(auto2gt_distances)))
gt2auto_distance_map_arr = sitk.GetArrayViewFromImage(gt2auto_distance_map)
gt2auto_distances = list(gt2auto_distance_map_arr[gt2auto_distance_map_arr!=0]) 
gt2auto_distances = gt2auto_distances + \
                            list(np.zeros(num_gt_surface_voxels - len(gt2auto_distances)))
            
all_surface_distances = auto2gt_distances + gt2auto_distances
```

Which gives me the following outputs:
- ground truth surface: 
![image](https://user-images.githubusercontent.com/93598891/157868269-8cd7ea28-f891-4067-bb29-74d9738ac7ac.png)
- num_gt_surface_voxels = 17367
- auto segmented surface:
![image](https://user-images.githubusercontent.com/93598891/157868342-bc6fb2d4-33e2-48cc-a0f3-2d1ea26e752c.png)
- num_auto_surface_voxels = 18984
- auto2gt_distances has a length of 9202 and are all mainly between 2.0 and 4.0 with some that are a bit larger (this would assume 18984-9202=9782 voxels in the surface that have a distance of zero)
- gt2auto_distances had a length of 6642 and are all mainly between 2.0 and 4.0 with some that are a bit larger (this would assume 17367-6642=10725 voxels in the surface that have a distance of zero)

The fraction of voxels with a distance of zero is in both cases higher than I would expect. More than half of the voxels is then exactly the same in both contours. Also, you would expect that the number of voxels with a distance of zero is the same for both lists of distances as a distance of zero from one contour to another is also zero from the other contour back. As 9782 and 10725 are not the same, this is not the case. 

I also tried to find these perfectly overlapping voxels in another way, not by making use of a distance map. Just by simply multiplying the two surfaces. Only the voxels that are present in both surfaces (i.e. zero-distance) should be kept and the others should be zero. This yielded the following image:

![image](https://user-images.githubusercontent.com/93598891/157870324-673e8377-7236-4c3c-af1b-4c91cde6d1ee.png)

And a value of 7494 voxels, which is substantially lower than what we have seen above (and therefore makes more sense to me). 

The following image shows the two surfaces and overlapping voxels even more intuitive:
 
![image](https://user-images.githubusercontent.com/93598891/157870447-bd78d0df-7a17-4492-9fa5-bff5f7d8d31b.png)

Now my question is, how is this possible? I checked most of the steps, but one thing I was not really able to check is the SignedMaurerDistanceMap. Does it indeed result in a distance of zero if, and only if, two voxels are at the exact same position? Or is one position off enough to cause a distance of zero?

Thank you in advance for thinking with me on this issue!

Best,
Ilva

**Comment by zivy** [comment]
Hello @IlvaHou55,

I suspect the differences you are seeing are due to the 3D nature of the data vs. the 2D visualizations that you are using. There are many more points with a distance zero because of this. Let's start by ensuring that the distance map and the surface are consistent (I suspect you'll be surprised by the surface, it isn't a set of contours on the axial slices, top-left view):

<img width="965" alt="Screen Shot 2022-03-13 at 3 38 19 PM" src="https://user-images.githubusercontent.com/338645/158076125-6ba14748-0187-4455-a898-b4443ac7df44.png">

The following code reads the numpy segmentations and saves the surface and distance maps for the ground truth and automated segmentation:
```
import SimpleITK as sitk
import numpy as np

def sitk_uint8_from_np(arr_file_name, origin, spacing, direction):
    image = sitk.GetImageFromArray(np.load(arr_file_name).transpose().astype(np.uint8))
    image.SetOrigin(origin)
    image.SetSpacing(spacing)
    image.SetDirection(direction)
    return image

origin = (-209.45181655884, -178.75591659546, 223.45248413086)
spacing = (2.0, 2.0, 4.0)
direction = (1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0)

auto_seg = sitk_uint8_from_np("auto_contour.npy", origin, spacing, direction)
gt_seg = sitk_uint8_from_np("gt_contour.npy", origin, spacing, direction)

gt_distance_map = sitk.Abs(sitk.SignedMaurerDistanceMap(gt_seg, squaredDistance=False, useImageSpacing=True))
gt_surface = sitk.LabelContour(gt_seg)
sitk.WriteImage(gt_distance_map, 'gt_distance.mha')
sitk.WriteImage(gt_surface, 'gt_surface.mha')

auto_distance_map = sitk.Abs(sitk.SignedMaurerDistanceMap(auto_seg, squaredDistance=False, useImageSpacing=True))
auto_surface = sitk.LabelContour(auto_seg)
sitk.WriteImage(auto_distance_map, 'auto_distance.mha')
sitk.WriteImage(auto_surface, 'auto_surface.mha')
```
Load the distance map into [ITK-SNAP](http://www.itksnap.org/pmwiki/pmwiki.php) and then load the surface as a segmentation. When you click on the surface voxel you will see that the intensity value underneath it (from the distance map) is zero. So the contour and distance map are in agreement.

What we also see from the image above is that there is a discontinuity in the ground truth segmentation, top-right side view. 

This evaluation is treating the segmentation as 3D and hence the surfaces do not necessarily yield contours when intersected with the axial slices. This is the correct thing to do, when working with 3D objects do the analysis in 3D. 

To get the results you want, you will need to work in a slice by slice fashion. The default approach is to use the axial slices, but there is no real scientific reason for that. From a scientific standpoint there is no preference to the axial vs. sagittal vs. coronal slices and each one will yield different results. Which one you use is up to you.

Finally, if you are interested in a visualization of reference vs. algorithmic results (showing agreement, over and under segmentation) take a look at the [visualization notebook](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/blob/master/Python/05_Results_Visualization.ipynb), "Comparing two segmentations" section.

**Comment by IlvaHou55** [comment]
@zivy thank you for thinking with me on this!

The fact that there is a difference between a 3D surface and a contour 'per-slice'  is something I also was aware of and already thought about. But I still would think that the number of zero-distance voxels is equal to the number of voxels in overlap with the two surfaces, because the way you calculate the overlapping voxels is also a 3D operation. So you will find the overlapping voxels in every dimension, which is also the reason that the number of zero-voxels (highlighted in yellow here) can be more than one voxel thick for the contours:
![image](https://user-images.githubusercontent.com/93598891/158127079-12d3a31b-f59a-481c-8d16-f4fc108dbf4a.png)

So, I still do not see why the '3D nature' would cause a difference in zero-distance voxels from the distance map versus the number of overlapping voxels between the surfaces (= distance of zero).

**Comment by zivy** [comment]
Hello @IlvaHou55,

Thanks for identifying this bug, will create a PR to fix it in the notebook. I would like to add you as a [co-author](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors). Could you share the email address associated with your GitHub account so that I can do so.

**Comment by IlvaHou55** [comment]
@zivy sure! I would like to keep my e-mail private, but according to the [co-author page](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors), this e-mail adress should work: 93598891+IlvaHou55@users.noreply.github.com
